name: Deploy
on:
  # Building on manual dispatch, and pushes to dev / main.
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
  cancel-in-progress: false

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    defaults:
      run:
        shell: bash -eo pipefail -l {0}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - id: 'google-cloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.WORKLOAD_IDENTITY_SA }}

      - id: 'google-cloud-sdk-setup'
        name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: 'gcloud docker auth'
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: "Set up Python"
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          enable-cache: true
          version: 0.9.13

      - name: Install the project
        run: uv sync --locked

      - name: Package Cloud Function Archive
        run: |
          cd stats_exporter
          zip source.zip main.py pyproject.toml


      - uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58 # v6.6.1
        with:
          command: up
          work-dir: ./infrastructure
          stack-name: ${{ vars.PULUMI_STACK_NAME }}
          cloud-url: ${{ vars.PULUMI_STATE_BUCKET }}
          parallel: 20 # Otherwise requests might time out.
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_CONFIG_GCP_REGION: ${{ vars.PULUMI_CONFIG_GCP_REGION }}
          PULUMI_CONFIG_GCP_PROJECT: ${{ secrets.PULUMI_CONFIG_GCP_PROJECT }}
          PULUMI_CONFIG_APP_DOMAIN: ${{ secrets.PULUMI_CONFIG_APP_DOMAIN }}
          PULUMI_CONFIG_SECURITY_POLICY_STACK: ${{ vars.PULUMI_CONFIG_PRIVATE_CONFIG_STACK }}
          APP_CONFIG_STATS_ARCHIVE_BUCKET: ${{ vars.APP_CONFIG_STATS_ARCHIVE_BUCKET }}
          APP_CONFIG_CLOUD_FUNCTION_SOURCE_BUCKET: ${{ vars.APP_CONFIG_CLOUD_FUNCTION_SOURCE_BUCKET }}
          APP_CONFIG_SLACK_CHANNEL_ID: ${{ secrets.APP_CONFIG_SLACK_CHANNEL_ID }}

          # skip checkpointing to speed-up the workflow, and avoid lots of saved state jsons
          PULUMI_SKIP_CHECKPOINTS: true
